[FE/07] 로그인 화면
Step3-kakao-tech-campus/Team15_FE pull request #27
Opened 2023-10-02 01:56 UTC by mlnwns

틀만 잡아둔 상태입니다. 추가하도록 하겠습니다.

2023-10-02 22:54 UTC, loopy-lim requested changes
몇가지가 수정되어야 할 것 같습니다!!
label을 쓰실때 참고로 useId를 이용하면 좋을 것 같습니다.

참고로 reiewers와 assignees, labels를 붙여주시면 감사하겠습니다.
또한 PR를 날리고 있으면 push할 때 동기화가 바로 되어 있어요!(뒤의 PR #29과 겹쳐 말씀드립니다) 
이 PR #27 을 추후 closed하고, 위의 PR로 #29 로 요구사항이 수정된 이후 PR #29 을 merge하겠습니다.

2023-10-02 22:54 UTC, loopy-lim commented on src/components/common/Input.component.jsx
> +  />
input과 label은 친구입니다!
어떻게 쓰면 좋을지 한번 고려해보면 좋을 것 같습니다
또한  type={type}은 너무 많은 것 같습니다... 저희가 쓰는 타입이 무엇인지 확인해보고 분리를 하는 것이 좋을 것 같습니다.

2023-10-02 22:54 UTC, loopy-lim commented on src/components/common/Input.component.jsx
> +  />
추가적으로 classnames라는 라이브러리를 사용하면 리터럴로 복잡하게 className을 쓰는 것이 아니라 쉽게 사용할 수 있습니다.

2023-10-02 22:54 UTC, loopy-lim commented on src/pages/Account.page.jsx
> +    <>
fragment가 왜 밖에 있나요?
노드가 많으면 많을 수록 성능이 느리기 때문에 제거하면 좋을 것 같습니다.

2023-10-02 22:54 UTC, loopy-lim commented on src/pages/Account.page.jsx
> +      >
공용 컴포넌트에 MainContainer라는 애가 있습니다!
(너무 같은거 같아 만들어 두었습니다)

2023-10-02 22:54 UTC, loopy-lim commented on src/pages/Login.page.jsx
> +        <BottomFullLink title="로그인" to={`/`} />
링크가 잘못 되어 있는것 같습니다!

2023-10-02 22:54 UTC, loopy-lim commented on src/pages/School.page.jsx
> +        <BottomFullLink title="다음으로" to={`/`} />
위와 같이 링크가 변경 되어야 할 것 같습니다!

2023-10-03 12:02 UTC, mlnwns commented on src/pages/Account.page.jsx
> +      >
공용 컴포넌트가 아직 추가된 상태가 아닌거같아 추후에 추가하도록 하겠습니다

2023-10-03 12:02 UTC, mlnwns commented on src/pages/Login.page.jsx
> +        <BottomFullLink title="로그인" to={`/`} />
로그인 페이지라 메인화면으로 넘어가도록 했습니다

2023-10-03 12:03 UTC, mlnwns commented on src/pages/School.page.jsx
> +        <BottomFullLink title="다음으로" to={`/`} />
SchoolCard로 링크가 가도록 변경했습니다

2023-10-03 12:05 UTC, mlnwns commented on src/components/common/Input.component.jsx
> +  />
classnames 라이브러리 사용법 숙지하겠습니다!

2023-10-04 05:20 UTC, minkonging approved these changes

2023-10-04 05:20 UTC, minkonging commented on src/components/common/Input.component.jsx
> +  />
classnames라는 라이브러리는 처음이네요 저도 한번 봐보겠습니다

2023-10-04 13:53 UTC, closed without merging