[FE/09] 페이머니 페이지 _ 상단부분 완성
Step3-kakao-tech-campus/Team15_FE pull request #28
Opened 2023-10-02 11:53 UTC by minkonging

식사시간 제외하고 허들로 민준님과 11시간동안 서로 모르는거 물어봐가면서 진행한 내용입니다.. 😭

페이머니내에서 api에서 어떤식으로 정보들 가져올건지 (useParam 부분)에서 좀 많은 시간을 쓴 것 같습니다.. **(해결했습니다!)**

##진행내용

페이머니 페이지의 상단부분(AppBar, 잔액 조회 화면, 출금 및 충전 버튼)의 CSS와 페이지 연결을 진행하였습니다.

현재 출금 및 충전 버튼의 존재 자체만 만들어두고

세부 사항(페이머니 페이지 하단 페이머니 내역 부분과 출금 및 충전 페이지)은 내일 진행할 예정입니다.

감사합니다

2023-10-02 23:01 UTC, loopy-lim requested changes
몇가지 수정상항이 있어 알려드립니다!!

2023-10-02 23:01 UTC, loopy-lim commented on src/components/paymoney/MoneyHistory.jsx
> +    };
react-query를 써보는 것은 어떻나요? (추후 API주면 바로 연결 쉽게 할 수 있을 것 같아요!
apis안에 보면 예시가 있어요!

2023-10-02 23:01 UTC, loopy-lim commented on src/components/paymoney/MoneyHistory.jsx
> +};
1. `bg-[#FCFCFC]`로 해야 적용이 되요!
2. `<></>`를 붙이신 이유는 무엇인가요?
3. 띄어쓰기를 신경써 주세요!
4. 끝에는 개행문자를 적어주세요!

2023-10-02 23:01 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +    };
navigate도 있지만 `<Link />`라는 애도 있답니다!

2023-10-02 23:01 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +                    <br />
여기의 같은 경우는 CSS로 처리하는게 저는 더 깔끔해 보이더라구요!!(flex라거나...?)

2023-10-02 23:01 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[350px] h-[80px]" style={{ display: 'flex', justifyContent: 'center' }}>
1. CSS를 쓰실 때  px를 쓰시는 이유가 무엇인가요?
2. style은 제거 해주시기 바랍니다(tailwind로 전환해주세요)

2023-10-03 07:39 UTC, minkonging reviewed
답변 완료 했습니당

2023-10-03 07:39 UTC, minkonging commented on src/components/paymoney/MoneyHistory.jsx
> +    };
옴.. productDetail 페이지 느낌을 따라한거라서요.. apis 파일이 어딘지 모르겠는데 경로 알려주실수있을까요 ?

2023-10-03 07:39 UTC, minkonging commented on src/components/paymoney/MoneyHistory.jsx
> +};
1. 아 그래서 적용이 안됐구나 😂
2. '페이머니 내역' 글자 부분이랑 언더바 까지를 한 묶음 처리하고 밑에 세부 내역들을 또 한 부분으로 두 뭉탱이 취급을 하려고 <>을 넣은 것 같아요
3. 띄어쓰기는 어떤 부분 말씀하시는 걸까요? </div> 밑줄 말씀하시는걸까요?
4. 제가 아는 개행문자는 \n인데 얘를 어디에 어떻게 하라는 말씀이실까요..?

2023-10-03 07:39 UTC, minkonging commented on src/components/paymoney/MyMoney.jsx
> +    };
바꾸는게 나을까요? Link to가 리액트를 쓰는 이유(화면 리랜더링 관련해서..)라고 하긴 하던데..
저는 navigate가 손에 더 익은 것 같은 느낌이라서요..

2023-10-03 07:39 UTC, minkonging commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[350px] h-[80px]" style={{ display: 'flex', justifyContent: 'center' }}>
1. 처음에는 w-1/5 느낌으로 하다가 figma에서는 378*78 이더라구요 그 페이머니 잔액 보는 회색 둥글 원 크기가!
  그래서 보다 정확한게 좋지 않을까 싶어서 일부러 저렇게 했습니당
2. 넵

2023-10-03 07:39 UTC, minkonging commented on src/components/paymoney/MyMoney.jsx
> +                    <br />
사실 이 부분은.. 저도 여러 시도 끝에 한거라.. 😂
다시 해보겠습니다..🥹

2023-10-03 07:42 UTC, loopy-lim commented on src/components/paymoney/MoneyHistory.jsx
> +    };
방금 알았어요... 제가 Merge를 main으로 해버렸네요 ㅠㅠ 회의 시간 전가지 week05로 PR 날리도록 하겠습니다.

2023-10-03 07:44 UTC, loopy-lim commented on src/components/paymoney/MoneyHistory.jsx
> +};
2. `<></>`는 parent가 1개이여야 한다라는 react의 조건에 따라서 붙여야 하는건데 여기에서는 자식도 1개라서 제거하는게 옳은거 같아요!
3. 22번째 줄에 띄어쓰기가 있어서 말한거에요!(의미없는 띄어쓰기는 가독성을 해친답니다!)
4. 어... EOL이라는 근데 [여기](https://velog.io/@doondoony/posix-eol)를 참고해주세요!

2023-10-03 07:45 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +    };
험... 사실 거의 같은거라고 저도 알고 있기는 한데, Link to 가 아무래도 나중에 자연스러운 트렌지션을 넣을 때 더 편하지 않을까 싶어서요!!
만약 넣고 싶다면 `<a>` tag를 이용해서 시멘틱을 어 넣는 것을 추천해요(그.. 접근성을 위한 것이에요!!)

2023-10-03 07:47 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[350px] h-[80px]" style={{ display: 'flex', justifyContent: 'center' }}>
어... 일단 px보단 rem을 추천 드려요! 그 이유는 [이런 블로그](https://onlydev.tistory.com/128#:~:text=rem%EC%9D%80%20%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EC%9D%98%20%EA%B8%B0%EB%B3%B8,%EB%B3%80%ED%95%B4%EC%95%BC%20%ED%95%98%EB%8A%94%20%EA%B3%B3%EC%97%90%20%EC%82%AC%EC%9A%A9%ED%95%9C%EB%8B%A4.)를 참고해보세요
참고로 저런 것을 만들고 싶다면 padding을 적극적으로 차용해보세요!

2023-10-03 12:06 UTC, mlnwns approved these changes

2023-10-04 04:36 UTC, merged

2023-10-04 05:14 UTC, mlnwns commented on src/components/paymoney/MoneyHistory.jsx
> +};
22번째 줄 띄어쓰기 같은 경우는 prettier이라는 확장 프로그램 쓰면 자동으로 가독성 좋게 바꿔주더라고요!