[FE/10] 충전페이지 보완 필요
Step3-kakao-tech-campus/Team15_FE pull request #46
Opened 2023-10-12 07:38 UTC by minkonging

##보완 필요한 내용

1. 키패드 연속으로 칠 수 있게끔 (숫자 버튼 하나 누를 때마다 키패드가 닫히는 상황)
  isOpen이 ChargePage에 있어야한다고 하셨는데 옮겨봤는데도 잘 모르겠습니다 ..
2. 충전하기 버튼 활성화 설정은 해놨는데 number을 못 읽어서 키패드 버튼을 눌러도 버튼이 활성화가 안되는 것 같습니다

이 부분만 완료되면 충전하기 버튼 활성화 됐을때 **모달창 제작 후 최종 PR** 하겠습니다

2023-10-12 08:30 UTC, loopy-lim requested changes
확인해주시면 감사하겠습니다.(만약 너무 힘들다 그러면 말씀해주세요~)
merge후에 제가 refactoring 하겠습니다

2023-10-12 08:30 UTC, loopy-lim commented on src/components/common/Txt.component.jsx
> +        marginRight && `mr-${marginRight}`,
빼주세요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
저번에 말했다 싶이 classname을 통해서 전달할 수 있습니다.
정말 심각한 에러를 만들 수 있어요(UI가 적용이 안된다거나...)

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/ChargeMoney.jsx
> +    );
eslinter와 prettier를 켜주세요

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/KeyPad.css
저희는 tailwind를 쓰고 있습니다.
css를 지양하도록 하는게 좋을것 같습니다.

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/KeyPad.jsx
> +            <button className="key clear" onClick={onClose}>x</button>
Icon을 이용해 주세요

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/KeyPad.jsx
> +    }
이거 또한 상위 컴포넌트에서 다루면 더 좋을 것 같기도 합니다.

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/MoneyHistory.jsx
> +            </div>
api를 통해서 미리 추상화를 하도록 하는게 더 좋을 것 같습니다.

2023-10-12 08:30 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[25rem] h-[5rem] flex justify-center">
크기를 지정하신 이유가 무엇인가요? flex를 쓴 김에 반응형을 조금은 신경쓰면서 하면 더 좋을 것 같아요

2023-10-12 08:30 UTC, loopy-lim commented on src/pages/Charge.page.jsx
> +            >
MainContainer로 변경해주세요(만들어두었습니다)

2023-10-12 08:30 UTC, loopy-lim commented on src/pages/Charge.page.jsx
> +                />
이거는 오히려 jotai를 이용하는 것도 나쁘지 않을 수 있어요

2023-10-12 10:09 UTC, merged

2023-10-13 01:05 UTC, minkonging commented on src/components/paymoney/ChargeMoney.jsx
> +    );
켜져있는거같은데 어떤 부분 때문에 그러시는 걸까요

2023-10-13 01:05 UTC, minkonging commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[25rem] h-[5rem] flex justify-center">
되게 스무고개 하는 느낌인데 미디어 쿼리 쓰라는 말씀이실까요?
원하시는게 정해져있는데 제가 헤매는 느낌이라 구체적인 피드백해주시면 더 빠른 진행에 도움이 될 것 같습니다
그리고 
사실 이것보다 앞서 말씀 드린 2개(키패드 연속 누르기, 충전하기 버튼 활성화)가 더 우선순위가 높다고 생각해서
지난 PR 피드백은 아직 반영이 안된 상태에요

2023-10-13 03:12 UTC, loopy-lim commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[25rem] h-[5rem] flex justify-center">
어... 스무고개가 아니라... 혹시 반응형에 대해서 어떻게 생각하시나요? 이에 대해서 어떤 생각을 가지고 있는지 궁금합니다.
그리고 일단 못한 이유에 대해서는 알겠습니다.
수정을 다 해서 PR을 날리도록 하겠습니다. CSS를 일부 수정 해두었으니(Mymoney컴포넌트네요) 참고하셔서 가면 좋을 것 같습니다.

2023-10-13 11:13 UTC, minkonging commented on src/components/paymoney/MyMoney.jsx
> +            <div className="bg-[#F1F1F1] p-2 m-6 rounded-lg w-[25rem] h-[5rem] flex justify-center">
음.. 저는 반응형에 대한 경험이 2단계 클론코딩때 밖에 없어서요
애초에 안드로이드 앱, 웹 기준으로만 만들었던터라

이 파트에서 처음에 px로 왜 쓰냐고 하셔서 피그마 ui 크기 맞춰서 px로 했다 말씀드렸었는데 
rem으로 하는게 좋을것같다하셔서 rem으로 했는데
반응형으로 하셨으면 좋겠다고 하셔서
미디어 쿼리를 말씀하시는건지..
그래서 스무고개라는 표현을 쓴겁니다

물론 웹뷰를 캐퍼시터를 통해서 앱으로 바꿀때 원활하게 하고자
반응형 말씀하시는 것 같은데
반응형에 대한 경험이 딱히 없어서 구체적인 피드백 해주시면 빠른 진행에 도움이 될것같다고 한거랍니다